window.LV=window.LV||[];
LV.push({
id:'inicial',name:'Inicial',code:'IN',cefr:'A1–A2',d:1,color:'#16a34a',
book:'Essential Grammar in Use',author:'Raymond Murphy',ed:'Cambridge',
file:'Essential Grammar in Use - Raymond Murphy - Inicial.pdf',pdf0:7,
desc:'A base do idioma: verbo <i>to be</i>, presente, passado, futuro, perguntas, artigos, pronomes e preposições. Para quem está começando ou quer revisar o essencial com segurança.',
units:["am/is/are","am/is/are (questions)","I am doing (present continuous)","are you doing? (present continuous questions)","I do/work/like etc. (present simple)","I don't ... (present simple negative)","Do you ...? (present simple questions)","I am doing and I do (present continuous and present simple)","I have ... / I've got ...","was/were","worked/got/went etc. (past simple)","I didn't ... / Did you ...? (past simple negative and questions)","I was doing (past continuous)","I was doing (past continuous) and I did (past simple)","I have done (present perfect 1)","I've just ... / I've already ... / I haven't ... yet (present perfect 2)","Have you ever ...? (present perfect 3)","How long have you ...? (present perfect 4)","for / since / ago","I have done (present perfect) and I did (past simple)","is done / was done (passive 1)","is being done / has been done (passive 2)","be/have/do in present and past tenses","Regular and irregular verbs","I used to ...","What are you doing tomorrow?","I'm going to ...","will/shall (1)","will/shall (2)","might","can and could","must / mustn't / needn't","should","I have to ...","Would you like ...? / I'd like ...","there is / there are","there was/were / there has/have been / there will be","It ...","I am / I don't etc.","Have you? / Are you? / Don't you? etc.","too/either / so am I / neither do I etc.","isn't / haven't / don't etc. (negatives)","is it ...? / have you ...? / do they ...? etc. (questions 1)","Who saw you? / Who did you see? (questions 2)","Who is she talking to? / What is it like? (questions 3)","What ...? / Which ...? / How ...?","How long does it take ...?","Do you know where ...? / I don't know what ... etc.","She said that ... / He told me that ...","work/working / go/going / do/doing","to ... (I want to do) and -ing (I enjoy doing)","I want you to ... / I told you to ...","I went to the shop to ...","go to ... / go on ... / go for ... / go -ing","get","do and make","have","I/me / he/him / they/them etc.","my/his/their etc.","Whose is this? It's mine/yours/hers etc.","I/me/my/mine","myself/yourself/themselves etc.","-'s (Ann's camera / my brother's car) etc.","a/an ...","flower(s) / bus(es) (singular and plural)","a car / some money (countable/uncountable 1)","a car / some money (countable/uncountable 2)","a/an and the","the ...","go to work / go home / go to the cinema","I like music / I hate exams","the ... (names of places)","this/that/these/those","one/ones","some and any","not + any / no / none","not + anybody/anyone/anything / nobody/no-one/nothing","somebody/anything/nowhere etc.","every and all","all / most / some / any / no/none","both / either / neither","a lot / much / many","(a) little / (a) few","old/nice/interesting etc. (adjectives)","quickly/badly/suddenly etc. (adverbs)","old/older / expensive/more expensive","older than ... / more expensive than ...","not as ... as","the oldest / the most expensive","enough","too","He speaks English very well. (word order 1)","always/usually/often etc. (word order 2)","still / yet / already","Give me that book! / Give it to me!","at 8 o'clock / on Monday / in April","from ... to / until / since / for","before / after / during / while","in / at / on (places 1)","in / at / on (places 2)","to / in / at (places 3)","under / behind / opposite etc. (prepositions)","up / over / through etc. (prepositions)","on / at / by / with / about (prepositions)","afraid of ... / good at ... etc. / preposition + -ing","listen to ... / look at ... etc. (verb + preposition)","go in / fall off / run away etc. (phrasal verbs 1)","put on your shoes / put your shoes on (phrasal verbs 2)","and / but / or / so / because","When ...","If we go ... / If you see ... etc.","If I had ... / If we went ... etc.","a person who ... / a thing that/which ... (relative clauses 1)","the people we met / the hotel you stayed at (relative clauses 2)"],
mods:[
{t:'Verbo to be (am / is / are)',u:[1,2],
intro:'O verbo <b>to be</b> significa <i>ser</i> e <i>estar</i>. É o verbo mais usado do inglês: serve para dizer nome, idade, profissão, origem, estado e localização.',
pts:[['As três formas no presente','<p><b>I am</b> · <b>he/she/it is</b> · <b>we/you/they are</b>. Na fala quase sempre usamos a forma curta: <i>I\'m, he\'s, she\'s, it\'s, we\'re, you\'re, they\'re</i>.</p>'],
['Negativa','<p>Coloque <b>not</b> depois do verbo: <i>I\'m not</i>, <i>he isn\'t</i> (= is not), <i>they aren\'t</i> (= are not). Não existe <i>amn\'t</i>: use <i>I\'m not</i>.</p>'],
['Perguntas e respostas curtas','<p>Inverta sujeito e verbo: <i>You are tired.</i> → <b>Are you</b> tired? Respostas curtas: <i>Yes, I am. / No, I\'m not.</i> Na resposta afirmativa curta não se usa contração: <i>Yes, I am</i> (e não <s>Yes, I\'m</s>).</p>'],
['Idade, fome, frio…','<p>Em inglês usamos <b>be</b> onde o português usa <i>ter</i>: <i>I\'m 25</i> (tenho 25 anos), <i>I\'m hungry</i> (estou com fome), <i>I\'m cold</i> (estou com frio), <i>Are you afraid?</i> (você está com medo?).</p>']],
ex:[['I\'m a student and my sister is a nurse.','Sou estudante e minha irmã é enfermeira.'],['We aren\'t from London. We\'re from Brazil.','Não somos de Londres. Somos do Brasil.'],['Is your father at home? — No, he isn\'t.','Seu pai está em casa? — Não, não está.'],['How old are you? — I\'m 30.','Quantos anos você tem? — Tenho 30.'],['Where are my keys?','Onde estão minhas chaves?']],
trap:['<s>I have 20 years.</s> → <b>I\'m 20 (years old).</b>','<s>Yes, I\'m.</s> → <b>Yes, I am.</b>','Não omita o verbo: <s>She very tired.</s> → <b>She\'s very tired.</b>'],
drill:[['My brother ___ a doctor.','is|\'s'],['I ___ hungry. Let\'s eat!','am|\'m'],['___ you from Spain?','are'],['They ___ (not) at school today.','aren\'t|are not|\'re not'],['How old ___ your parents?','are'],['It ___ (not) cold today.','isn\'t|is not|\'s not']],
quiz:[['Escolha a frase correta:',['I have 18 years.','I am 18 years.','I\'m 18.','I\'m have 18.'],2,'Idade usa <b>be</b>: <i>I\'m 18</i> ou <i>I\'m 18 years old</i>.'],
['___ your sister a teacher?',['Is','Are','Am','Does'],0,'<i>your sister</i> = she → <b>is</b>.'],
['Resposta curta correta para "Are you tired?":',['Yes, I\'m.','Yes, I am.','Yes, I\'m tired am.','Yes, I do.'],1,'Na resposta curta afirmativa não se contrai: <i>Yes, I am.</i>'],
['Negativa de "We are late":',['We not late.','We don\'t late.','We aren\'t late.','We isn\'t late.'],2,'<b>are not</b> → <b>aren\'t</b>.']],
cards:[['I am / you are / he is','Eu sou(estou) / você é / ele é'],['isn\'t / aren\'t','is not / are not'],['I\'m hungry.','Estou com fome.'],['How old are you?','Quantos anos você tem?'],['Are you OK? — Yes, I am.','Você está bem? — Sim, estou.']]},

{t:'Present continuous',u:[3,4],
intro:'O <b>present continuous</b> (<i>I am doing</i>) descreve uma ação que está acontecendo agora, no momento da fala, ou neste período.',
pts:[['Forma','<p><b>am/is/are + verbo-ing</b>: <i>I\'m working</i>, <i>she\'s reading</i>, <i>they\'re playing</i>.</p>'],
['Regras do -ing','<p>A maioria só recebe -ing (<i>read → reading</i>). Verbo terminado em <b>-e</b> perde o e (<i>make → making</i>). Sílaba curta consoante-vogal-consoante dobra a última letra (<i>run → running, sit → sitting</i>). <i>lie → lying</i>.</p>'],
['Perguntas','<p>Inverta o <i>be</i>: <b>Are you</b> listening? <b>What is</b> she doing? <b>Where are</b> they going?</p>'],
['Quando usar','<p>Para algo em andamento agora (<i>Look! It\'s raining.</i>) ou num período atual, mesmo que não seja neste segundo (<i>I\'m reading a great book this week.</i>).</p>']],
ex:[['Please be quiet. The baby is sleeping.','Por favor, faça silêncio. O bebê está dormindo.'],['What are you doing? — I\'m cooking dinner.','O que você está fazendo? — Estou fazendo o jantar.'],['She isn\'t working today.','Ela não está trabalhando hoje.'],['Why are you running?','Por que você está correndo?'],['We\'re learning English this year.','Estamos aprendendo inglês este ano.']],
trap:['Não esqueça o <i>be</i>: <s>I working.</s> → <b>I\'m working.</b>','<s>She is siting.</s> → <b>She is sitting.</b> (dobra o t)'],
drill:[['Look! It ___ (rain).','\'s raining|is raining'],['I ___ (watch) TV right now.','\'m watching|am watching'],['Are you ___ (listen) to me?','listening'],['They ___ (not / work) today.','aren\'t working|are not working|\'re not working'],['What ___ she doing?','is'],['He ___ (sit) next to the window.','\'s sitting|is sitting']],
quiz:[['"Ela está lendo agora." em inglês:',['She reads now.','She is reading now.','She reading now.','She is read now.'],1,'Ação em andamento: <b>is reading</b>.'],
['Forma -ing correta de "swim":',['swiming','swimming','swimeing','swimmming'],1,'Consoante-vogal-consoante → dobra: <b>swimming</b>.'],
['Pergunta correta:',['What you are doing?','What are you doing?','What do you doing?','What you doing are?'],1,'Pergunta: palavra interrogativa + <b>are</b> + sujeito + -ing.'],
['"Shh! The children ___."',['sleep','sleeps','are sleeping','is sleeping'],2,'<i>children</i> é plural → <b>are sleeping</b>.']],
cards:[['I\'m working.','Estou trabalhando.'],['make → ?','making'],['run → ?','running'],['What are you doing?','O que você está fazendo?'],['It\'s raining.','Está chovendo.']]},

{t:'Present simple',u:[5,7],
intro:'O <b>present simple</b> (<i>I work</i>) fala de hábitos, rotinas, fatos e verdades gerais: coisas que acontecem sempre ou com frequência.',
pts:[['O -s da terceira pessoa','<p>Com <b>he/she/it</b> o verbo ganha <b>-s</b>: <i>I work → she works</i>. Terminações -s, -sh, -ch, -x, -o ganham <b>-es</b> (<i>watches, goes, does</i>). Consoante + y vira <b>-ies</b> (<i>study → studies</i>). <i>have → has</i>.</p>'],
['Negativa com don\'t / doesn\'t','<p><i>I/you/we/they</i> <b>don\'t</b> + verbo; <i>he/she/it</i> <b>doesn\'t</b> + verbo <u>sem -s</u>: <i>She doesn\'t like coffee</i> (e não <s>doesn\'t likes</s>).</p>'],
['Perguntas com do / does','<p><b>Do</b> you live here? <b>Does</b> he speak French? <b>What time do</b> you get up? Depois de <i>does</i>, o verbo fica sem -s.</p>'],
['Advérbios de frequência','<p><i>always, usually, often, sometimes, rarely, never</i> ficam antes do verbo principal: <i>I usually walk to work.</i></p>']],
ex:[['I work in a bank. My wife works in a hospital.','Trabalho num banco. Minha esposa trabalha num hospital.'],['Water boils at 100 degrees.','A água ferve a 100 graus.'],['He doesn\'t eat meat.','Ele não come carne.'],['Do you speak English? — Yes, I do.','Você fala inglês? — Sim, falo.'],['What time does the shop open?','Que horas a loja abre?']],
trap:['<s>She work every day.</s> → <b>She works</b> every day.','<s>Does she works?</s> → <b>Does she work?</b>','<s>I no like it.</s> → <b>I don\'t like it.</b>'],
drill:[['My father ___ (drive) a taxi.','drives'],['She ___ (watch) TV every night.','watches'],['I ___ (not / like) cold weather.','don\'t like|do not like'],['He ___ (not / speak) Spanish.','doesn\'t speak|does not speak'],['___ you play the guitar?','do'],['What time ___ the film start?','does']],
quiz:[['Escolha a correta:',['He go to school by bus.','He goes to school by bus.','He going to school by bus.','He gos to school by bus.'],1,'Terceira pessoa: <b>goes</b>.'],
['Negativa correta:',['She don\'t like fish.','She doesn\'t likes fish.','She doesn\'t like fish.','She not like fish.'],2,'<b>doesn\'t + verbo base</b>.'],
['___ your brother live in London?',['Do','Does','Is','Are'],1,'<i>your brother</i> = he → <b>Does</b>.'],
['"study" na 3ª pessoa:',['studys','studyes','studies','studis'],2,'Consoante + y → <b>-ies</b>.']],
cards:[['I work / she works','Eu trabalho / ela trabalha'],['don\'t / doesn\'t','do not / does not'],['Do you…? / Does he…?','Você…? / Ele…? (perguntas)'],['always · usually · often · sometimes · never','sempre · geralmente · frequentemente · às vezes · nunca'],['have → he ___','has']]},

{t:'Presente simples × contínuo; have / have got',u:[8,9],
intro:'Aqui você aprende a escolher entre <i>I do</i> e <i>I am doing</i>, e a usar <b>have</b> e <b>have got</b> para posse.',
pts:[['Agora × sempre','<p><b>Contínuo</b>: acontecendo agora ou temporário (<i>I\'m wearing a jacket today</i>). <b>Simples</b>: hábito, rotina ou fato (<i>I usually wear jeans</i>).</p>'],
['Verbos de estado','<p>Alguns verbos quase nunca vão para o contínuo, mesmo falando de agora: <i>like, love, hate, want, need, know, understand, remember, mean, believe</i>. <i>I know</i> (e não <s>I\'m knowing</s>).</p>'],
['have × have got','<p>Para posse, família e doenças os dois funcionam: <i>I have a car = I\'ve got a car</i>. Negativa: <i>I don\'t have / I haven\'t got</i>. Pergunta: <i>Do you have…? / Have you got…?</i></p>'],
['have para ações','<p>Em ações (<i>have breakfast, have a shower, have a good time</i>) use só <b>have</b>, nunca <i>have got</i>. E essas ações podem ir para o contínuo: <i>I\'m having lunch.</i></p>']],
ex:[['I usually drink tea, but today I\'m drinking coffee.','Geralmente tomo chá, mas hoje estou tomando café.'],['Do you understand me?','Você me entende?'],['She\'s got two brothers.','Ela tem dois irmãos.'],['We don\'t have much time.','Não temos muito tempo.'],['They\'re having dinner now.','Eles estão jantando agora.']],
trap:['<s>I\'m wanting a coffee.</s> → <b>I want a coffee.</b>','<s>I have got breakfast at 8.</s> → <b>I have breakfast at 8.</b>'],
drill:[['Please be quiet. I ___ (work).','\'m working|am working'],['She ___ (work) in an office every day.','works'],['I ___ (not / understand) this word.','don\'t understand|do not understand'],['___ you got a pen?','have'],['He ___ (not / have) a car.','doesn\'t have|does not have|hasn\'t got|has not got'],['We ___ (have) lunch at the moment.','\'re having|are having']],
quiz:[['Qual está correta?',['I\'m knowing the answer.','I know the answer.','I knowing the answer.','I am know the answer.'],1,'<i>know</i> é verbo de estado.'],
['"Ela tem olhos azuis":',['She has got blue eyes.','She is having blue eyes.','She have blue eyes.','She got have blue eyes.'],0,'Posse/característica: <b>has got</b> ou <b>has</b>.'],
['"Normally I ___ to work, but today I ___ the bus."',['walk / take','am walking / take','walk / \'m taking','\'m walking / \'m taking'],2,'Rotina = simples; hoje = contínuo.'],
['Ação com have:',['I\'ve got a shower every morning.','I have a shower every morning.','I having a shower every morning.','I has a shower every morning.'],1,'Ação: só <b>have</b>.']],
cards:[['verbos de estado','like, want, need, know, understand, believe…'],['I\'ve got = ?','I have'],['have breakfast','tomar café da manhã'],['Have you got…? / Do you have…?','Você tem…?'],['I don\'t understand.','Não entendo.']]},

{t:'Passado: was / were e past simple',u:[10,12],
intro:'Para falar do que aconteceu e terminou no passado: <b>was/were</b> (passado de <i>be</i>) e o <b>past simple</b> dos outros verbos.',
pts:[['was / were','<p><i>I/he/she/it</i> <b>was</b> · <i>we/you/they</i> <b>were</b>. Negativa: <i>wasn\'t / weren\'t</i>. Pergunta: <i>Were you at home?</i></p>'],
['Verbos regulares e irregulares','<p>Regulares ganham <b>-ed</b> (<i>work → worked, stop → stopped, study → studied</i>). Irregulares têm forma própria e precisam ser memorizados: <i>go → went, see → saw, buy → bought, have → had, get → got</i>.</p>'],
['Negativa e pergunta com did','<p><b>didn\'t</b> + verbo base: <i>I didn\'t go</i>. Pergunta: <b>Did</b> you see it? <i>What did you buy?</i> Depois de <i>did</i>, o verbo volta para a forma base.</p>'],
['Marcadores de tempo','<p><i>yesterday, last night, last week, two days ago, in 2010, when I was a child</i>.</p>']],
ex:[['I was tired yesterday.','Eu estava cansado ontem.'],['We went to the beach last weekend.','Fomos à praia no último fim de semana.'],['She didn\'t call me.','Ela não me ligou.'],['Did you enjoy the film?','Você gostou do filme?'],['Where were you last night?','Onde você estava ontem à noite?']],
trap:['<s>Did you went?</s> → <b>Did you go?</b>','<s>I didn\'t saw him.</s> → <b>I didn\'t see him.</b>','<s>They was here.</s> → <b>They were here.</b>'],
drill:[['I ___ (be) at home last night.','was'],['They ___ (be) very happy.','were'],['We ___ (go) to Paris in 2019.','went'],['She ___ (not / come) to the party.','didn\'t come|did not come'],['___ you see the match yesterday?','did'],['He ___ (buy) a new phone last week.','bought']],
quiz:[['Passado de "see":',['seed','saw','seen','sawed'],1,'Irregular: <b>see – saw – seen</b>.'],
['Pergunta correta:',['Did she called you?','Did she call you?','Does she called you?','She did call you?'],1,'<b>Did + verbo base</b>.'],
['"Nós estávamos cansados":',['We was tired.','We were tired.','We are tired.','We did tired.'],1,'<i>we</i> → <b>were</b>.'],
['Negativa de "I bought it":',['I didn\'t bought it.','I don\'t bought it.','I didn\'t buy it.','I not bought it.'],2,'<b>didn\'t + buy</b>.']],
cards:[['go → ?','went'],['have → ?','had'],['buy → ?','bought'],['I didn\'t…','Eu não… (passado)'],['…ago','…atrás (two days ago = dois dias atrás)']]},

{t:'Past continuous',u:[13,14],
intro:'O <b>past continuous</b> (<i>I was doing</i>) mostra uma ação em andamento num momento do passado, muitas vezes interrompida por outra.',
pts:[['Forma','<p><b>was/were + -ing</b>: <i>I was reading, they were playing</i>. Negativa: <i>wasn\'t/weren\'t + -ing</i>. Pergunta: <i>What were you doing?</i></p>'],
['Ação em andamento','<p><i>At 8 o\'clock last night I was having dinner.</i> A ação já tinha começado e ainda não tinha terminado às 8h.</p>'],
['Contínuo + simples','<p>A ação longa no contínuo é interrompida por uma curta no simples: <i>I <b>was walking</b> home when it <b>started</b> to rain.</i> Com <i>when</i> + ação curta, ou <i>while</i> + ação longa.</p>']],
ex:[['What were you doing at 10 o\'clock?','O que você estava fazendo às 10 horas?'],['It was raining when we left.','Estava chovendo quando saímos.'],['I was cooking when the phone rang.','Eu estava cozinhando quando o telefone tocou.'],['They weren\'t listening.','Eles não estavam ouvindo.'],['While she was sleeping, someone called.','Enquanto ela dormia, alguém ligou.']],
trap:['<s>When I arrived, they had dinner.</s> (significa que jantaram depois) → <b>they were having dinner</b> (já estavam jantando).','Verbos de estado continuam no simples: <s>I was knowing</s> → <b>I knew</b>.'],
drill:[['At 9 pm I ___ (watch) TV.','was watching'],['They ___ (play) football when it started to rain.','were playing'],['What ___ you doing at 8 pm yesterday?','were'],['She ___ (not / listen) to the teacher.','wasn\'t listening|was not listening'],['I ___ (see) Tom while I was walking in the park.','saw'],['The phone rang while I ___ (have) a shower.','was having']],
quiz:[['"Eu estava dormindo quando você ligou."',['I slept when you were calling.','I was sleeping when you called.','I was sleep when you called.','I sleeping when you called.'],1,'Ação longa (contínuo) + interrupção (simples).'],
['Escolha:',['They was working.','They were working.','They were work.','They working.'],1,'<i>they</i> → <b>were</b> + -ing.'],
['"While I ___ dinner, I ___ my finger."',['cooked / was cutting','was cooking / cut','was cooking / was cutting','cooked / cut'],1,'Ação longa: <i>was cooking</i>; curta: <i>cut</i>.'],
['Pergunta correta:',['What you were doing?','What were you doing?','What did you doing?','What was you doing?'],1,'<b>What + were + you + -ing</b>.']],
cards:[['I was doing','Eu estava fazendo'],['when + ação curta','I was reading when he arrived.'],['while + ação longa','While I was reading, he arrived.'],['wasn\'t / weren\'t','was not / were not'],['What were you doing?','O que você estava fazendo?']]},

{t:'Present perfect',u:[15,20],
intro:'O <b>present perfect</b> (<i>I have done</i>) liga o passado ao presente: experiências, resultados que importam agora e situações que continuam até hoje. Não tem equivalente direto em português.',
pts:[['Forma','<p><b>have/has + particípio</b>: <i>I have (I\'ve) finished, she has (she\'s) lost her key</i>. Particípios irregulares: <i>be → been, go → gone, see → seen, do → done, eat → eaten</i>.</p>'],
['Resultado agora / just, already, yet','<p><i>I\'ve lost my key</i> (ainda não achei). <b>just</b> = acabou de (<i>I\'ve just eaten</i>); <b>already</b> = já, antes do esperado; <b>yet</b> = ainda/já em negativas e perguntas, no fim da frase (<i>Have you finished yet? I haven\'t finished yet.</i>).</p>'],
['Experiência: ever / never','<p><i>Have you <b>ever</b> been to Japan?</i> (alguma vez na vida). <i>I\'ve <b>never</b> eaten sushi.</i> Note: <i>been to</i> = foi e voltou; <i>gone to</i> = foi e ainda está lá.</p>'],
['Duração: how long, for, since','<p><i>How long have you lived here? I\'ve lived here <b>for</b> five years / <b>since</b> 2019.</i> <b>for</b> + período; <b>since</b> + ponto de início. Já <b>ago</b> vai com o passado simples: <i>I came here five years ago.</i></p>'],
['Present perfect × past simple','<p>Com tempo terminado (<i>yesterday, last year, in 2010, ago</i>) use o <b>past simple</b>: <s>I have seen him yesterday</s> → <i>I saw him yesterday.</i> Sem tempo definido, ligado ao agora: present perfect.</p>']],
ex:[['I\'ve just had lunch.','Acabei de almoçar.'],['Have you ever been to Brazil?','Você já foi ao Brasil?'],['She hasn\'t called yet.','Ela ainda não ligou.'],['We\'ve known each other since 2015.','Nós nos conhecemos desde 2015.'],['I saw that film last week.','Vi esse filme semana passada.']],
trap:['<s>I live here since 2010.</s> → <b>I\'ve lived here since 2010.</b>','<s>I have seen her yesterday.</s> → <b>I saw her yesterday.</b>','<s>since three years</s> → <b>for three years</b>'],
drill:[['I ___ (lose) my phone. I can\'t find it.','\'ve lost|have lost'],['Have you ever ___ (be) to London?','been'],['She has lived here ___ 2018.','since'],['They\'ve been married ___ ten years.','for'],['I ___ (see) him two days ago.','saw'],['He hasn\'t finished his homework ___.','yet']],
quiz:[['"Moro aqui há 3 anos."',['I live here for 3 years.','I\'ve lived here for 3 years.','I lived here since 3 years.','I\'m living here since 3 years.'],1,'Duração até agora: <b>present perfect + for</b>.'],
['Com "yesterday" usamos:',['I have bought it yesterday.','I bought it yesterday.','I\'ve buy it yesterday.','I have buyed it yesterday.'],1,'Tempo terminado → <b>past simple</b>.'],
['since ou for: "___ last Monday"',['for','since','ago','during'],1,'Ponto de início → <b>since</b>.'],
['"Ela foi para a França (e está lá)":',['She has been to France.','She has gone to France.','She went to France yesterday.','She is gone France.'],1,'<b>gone</b> = foi e ainda não voltou.']],
cards:[['I\'ve just…','Acabei de…'],['already / yet','já / ainda (neg.) ou já (perg.)'],['Have you ever…?','Você já… (alguma vez)?'],['for / since','por (duração) / desde (início)'],['been to × gone to','foi e voltou × foi e está lá']]},

{t:'Voz passiva, formas verbais e used to',u:[21,25],
intro:'A <b>voz passiva</b> foca em quem sofre a ação. Neste módulo você também revisa <i>be/have/do</i>, verbos irregulares e <b>used to</b> para hábitos do passado.',
pts:[['Passiva básica','<p><b>be + particípio</b>. Presente: <i>English <b>is spoken</b> here.</i> Passado: <i>The house <b>was built</b> in 1990.</i> Para dizer quem fez, use <b>by</b>: <i>The book was written by Orwell.</i></p>'],
['Outras passivas','<p>Contínua: <i>The road <b>is being repaired</b>.</i> Perfeita: <i>My bike <b>has been stolen</b>.</i></p>'],
['be, have e do como auxiliares','<p><b>be</b> forma o contínuo e a passiva; <b>have</b> forma o perfect; <b>do/does/did</b> formam perguntas e negativas do simples.</p>'],
['used to','<p>Hábito ou situação do passado que não existe mais: <i>I <b>used to</b> smoke</i> (eu fumava). Negativa: <i>I didn\'t use to</i>. Pergunta: <i>Did you use to…?</i></p>']],
ex:[['This room is cleaned every day.','Esta sala é limpa todos os dias.'],['My car was stolen last night.','Meu carro foi roubado ontem à noite.'],['The bridge is being painted.','A ponte está sendo pintada.'],['I used to live in a small town.','Eu morava numa cidade pequena.'],['Did you use to play football?','Você jogava futebol?']],
trap:['<s>The letter was send.</s> → <b>was sent</b> (particípio).','<s>I use to go there when I was a child.</s> → <b>I used to go</b>.'],
drill:[['Paper ___ (make) from wood.','is made'],['The window ___ (break) yesterday.','was broken'],['This song ___ (write) by John Lennon.','was written'],['I ___ (use) to have long hair.','used'],['My phone ___ (steal)! (present perfect passivo)','has been stolen'],['He didn\'t ___ to like vegetables.','use']],
quiz:[['Passiva de "They built the house in 1990":',['The house built in 1990.','The house was built in 1990.','The house is built in 1990.','The house was build in 1990.'],1,'Passado: <b>was + built</b>.'],
['"Eu morava em Paris":',['I use to live in Paris.','I used to live in Paris.','I was used to live in Paris.','I used to living in Paris.'],1,'<b>used to + verbo base</b>.'],
['"A estrada está sendo consertada":',['The road is repairing.','The road is being repaired.','The road is repaired being.','The road being repaired.'],1,'Passiva contínua: <b>is being + particípio</b>.'],
['Particípio de "write":',['wrote','writed','written','writing'],2,'<b>write – wrote – written</b>.']],
cards:[['is made / was made','é feito / foi feito'],['by …','por … (quem fez)'],['has been stolen','foi roubado (recentemente)'],['I used to…','Eu costumava… / eu …-ava'],['write – wrote – written','escrever']]},

{t:'Futuro: going to, will e presente contínuo',u:[26,29],
intro:'O inglês tem várias formas de futuro. A escolha depende de ser um plano, uma decisão na hora, uma previsão ou um compromisso marcado.',
pts:[['Compromisso marcado: presente contínuo','<p><i>I\'m meeting Ana tomorrow.</i> Use para combinados com hora e lugar.</p>'],
['Plano / intenção: going to','<p><b>am/is/are going to + verbo</b>: <i>I\'m going to buy a car.</i> Também para previsão com evidência: <i>Look at those clouds. It\'s going to rain.</i></p>'],
['Decisão na hora e previsão: will','<p><i>The phone is ringing. — I\'ll answer it.</i> (decidiu agora). <i>I think you\'ll like it.</i> Negativa: <b>won\'t</b>. Use também para oferecer e prometer: <i>I\'ll help you.</i></p>'],
['shall','<p>Em perguntas com <i>I/we</i> para oferecer ou sugerir: <i><b>Shall</b> I open the window? <b>Shall</b> we go?</i></p>']],
ex:[['What are you doing tonight?','O que você vai fazer hoje à noite?'],['I\'m going to study medicine.','Vou estudar medicina.'],['It\'s cold. I\'ll close the door.','Está frio. Vou fechar a porta.'],['I won\'t tell anyone.','Não vou contar a ninguém.'],['Shall we have a break?','Vamos fazer uma pausa?']],
trap:['<s>I will to go.</s> → <b>I will go.</b>','<s>I\'m going to the cinema tomorrow</s> está certo (compromisso); <s>I go to the cinema tomorrow</s> soa estranho.'],
drill:[['I\'m tired. I think I ___ go to bed. (decisão agora)','\'ll|will'],['Look at the sky! It ___ (rain). (evidência)','\'s going to rain|is going to rain'],['We ___ (meet) Tom at 7 tomorrow. (combinado)','\'re meeting|are meeting'],['I promise I ___ (not) be late.','won\'t|will not'],['___ I carry your bag? (oferta)','shall'],['She ___ (buy) a new car next month. (plano)','\'s going to buy|is going to buy']],
quiz:[['O telefone toca: "___ answer it!"',['I\'m going to','I\'ll','I answer','I\'m answering'],1,'Decisão no momento: <b>will</b>.'],
['Plano já decidido:',['I\'ll learn Spanish next year — decidi hoje.','I\'m going to learn Spanish next year.','I learn Spanish next year.','I learning Spanish next year.'],1,'Intenção: <b>going to</b>.'],
['Negativa de will:',['willn\'t','don\'t will','won\'t','will\'nt'],2,'<b>will not = won\'t</b>.'],
['"Vamos sair?" (sugestão):',['Will we go out?','Shall we go out?','Do we go out?','Are we go out?'],1,'Sugestão: <b>Shall we…?</b>']],
cards:[['I\'m going to…','Vou… (plano)'],['I\'ll…','Vou… (decisão agora/promessa)'],['won\'t','will not'],['Shall I…?','Quer que eu…?'],['I\'m meeting her tomorrow.','Vou me encontrar com ela amanhã (combinado).']]},

{t:'Verbos modais',u:[30,35],
intro:'Os <b>modais</b> (<i>can, could, might, must, should, have to, would</i>) expressam habilidade, permissão, possibilidade, obrigação e conselho. Vêm sempre seguidos do verbo base, sem <i>to</i> (exceto <i>have to</i>).',
pts:[['can / could','<p>Habilidade e permissão: <i>I <b>can</b> swim. <b>Can</b> I sit here?</i> Passado de habilidade: <i>I <b>could</b> read when I was four.</i> Pedido educado: <i><b>Could</b> you help me?</i></p>'],
['might','<p>Possibilidade (talvez): <i>It <b>might</b> rain later.</i> = Talvez chova.</p>'],
['must / mustn\'t / needn\'t / have to','<p><b>must</b> e <b>have to</b>: obrigação (<i>I must go / I have to work on Saturday</i>). <b>mustn\'t</b> = proibido (<i>You mustn\'t smoke here</i>). <b>don\'t have to / needn\'t</b> = não precisa (<i>You don\'t have to come</i>).</p>'],
['should e would like','<p><b>should</b> = conselho (<i>You should see a doctor</i>). <b>Would you like…?</b> = quer…? (oferta educada); <b>I\'d like</b> = eu gostaria (pedido educado).</p>']],
ex:[['Can you speak Italian?','Você sabe falar italiano?'],['We might go to the beach tomorrow.','Talvez a gente vá à praia amanhã.'],['You mustn\'t park here.','Você não pode estacionar aqui.'],['You don\'t have to pay. It\'s free.','Você não precisa pagar. É grátis.'],['I\'d like a glass of water, please.','Eu gostaria de um copo d\'água, por favor.']],
trap:['<s>I can to swim.</s> → <b>I can swim.</b>','<s>She musts go.</s> → <b>She must go.</b> (modal não leva -s)','<b>mustn\'t</b> (proibido) ≠ <b>don\'t have to</b> (não é necessário).'],
drill:[['___ you help me, please? (pedido educado)','could|can'],['It ___ snow tonight. I\'m not sure. (talvez)','might'],['You ___ smoke in the hospital. (proibido)','mustn\'t|must not'],['You look tired. You ___ go to bed.','should'],['I ___ to work tomorrow. It\'s Saturday, but I have a meeting.','have'],['___ you like some tea?','would']],
quiz:[['"Você não precisa vir" =',['You mustn\'t come.','You don\'t have to come.','You can\'t come.','You shouldn\'t come.'],1,'Ausência de obrigação: <b>don\'t have to</b>.'],
['Escolha a correta:',['She can sings.','She cans sing.','She can sing.','She can to sing.'],2,'Modal + verbo base, sem -s.'],
['Conselho:',['You should drink more water.','You would drink more water.','You might drink more water.','You can to drink more water.'],0,'Conselho: <b>should</b>.'],
['"Eu gostaria de um café":',['I like a coffee.','I\'d like a coffee.','I\'m liking a coffee.','I would to like a coffee.'],1,'Pedido educado: <b>I\'d like</b>.']],
cards:[['can / could','posso, sei / podia, conseguia'],['might','talvez, pode ser que'],['mustn\'t × don\'t have to','proibido × não precisa'],['should','deveria (conselho)'],['Would you like…?','Você gostaria de / quer…?']]},

{t:'There is, it e verbos auxiliares',u:[36,41],
intro:'Como dizer que algo <b>existe</b> (<i>there is/are</i>), usar <b>it</b> como sujeito vazio e responder rápido com auxiliares (<i>So do I, Neither can I</i>).',
pts:[['there is / there are','<p>Para "há/tem/existe": <i><b>There\'s</b> a bank near here. <b>There are</b> two cafés.</i> Passado: <i>there was/were</i>. Futuro: <i>there will be</i>. Perfect: <i>there has/have been</i>.</p>'],
['it como sujeito','<p>Inglês exige sujeito. Para tempo, distância, horas e datas use <b>it</b>: <i><b>It\'s</b> raining. <b>It\'s</b> 3 o\'clock. <b>It\'s</b> a long way.</i> E para opinião: <i>It\'s difficult to learn Chinese.</i></p>'],
['Respostas curtas e eco','<p>Repita só o auxiliar: <i>Do you like it? — Yes, I do.</i> Para reagir: <i>I\'m tired. — <b>Are you?</b></i> (sério?).</p>'],
['too / either / so / neither','<p>Concordar com afirmação: <i>I\'m hungry. — <b>So am I</b> / Me too.</i> Com negação: <i>I can\'t swim. — <b>Neither can I</b> / I can\'t either.</i></p>']],
ex:[['There\'s a problem with my computer.','Tem um problema no meu computador.'],['There were a lot of people at the party.','Havia muita gente na festa.'],['It\'s very hot today.','Está muito quente hoje.'],['I live in São Paulo. — So do I!','Moro em São Paulo. — Eu também!'],['She didn\'t go. — Neither did I.','Ela não foi. — Nem eu.']],
trap:['<s>Have a bank near here.</s> → <b>There\'s a bank near here.</b>','<s>Is raining.</s> → <b>It\'s raining.</b>','<s>There is two cars.</s> → <b>There are two cars.</b>'],
drill:[['___ are three bedrooms in the flat.','there'],['___ \'s cold today, isn\'t it?','it'],['There ___ a lot of rain last night.','was'],['I\'m from Brazil. — So ___ I.','am'],['I don\'t like coffee. — Neither ___ I.','do'],['I can\'t drive. — I can\'t ___.','either']],
quiz:[['"Tem um mercado aqui perto."',['Has a market near here.','There is a market near here.','It is a market near here.','There are a market near here.'],1,'Existência: <b>there is</b>.'],
['"I\'m not hungry." — "___"',['So am I.','Neither am I.','Neither I am.','So I am not.'],1,'Concordar com negativa: <b>Neither am I</b>.'],
['"___ is 10 km to the airport."',['There','It','This','He'],1,'Distância: <b>It</b>.'],
['Eco de surpresa: "I won the lottery!" — "___"',['Did you?','Do you?','Won you?','Are you?'],0,'Repete o auxiliar do passado: <b>Did you?</b>']],
cards:[['There is / There are','Há, tem (existe)'],['There was / were','Havia, tinha'],['It\'s raining.','Está chovendo.'],['So do I. / Me too.','Eu também.'],['Neither do I. / Me neither.','Nem eu.']]},

{t:'Negativas e perguntas',u:[42,49],
intro:'Monte negativas e perguntas sem erro: ordem das palavras, perguntas com preposição no final, <i>who</i> como sujeito ou objeto, perguntas indiretas e discurso indireto simples.',
pts:[['Regra geral','<p>Com auxiliar (<i>be, have, can, will</i>) basta inverter: <i>Can you…?</i> Sem auxiliar, use <b>do/does/did</b>: <i>Where do you live? Did she call?</i></p>'],
['Who sujeito × objeto','<p><i><b>Who saw</b> you?</i> (quem é o sujeito → sem <i>did</i>). <i><b>Who did</b> you <b>see</b>?</i> (quem é objeto → com <i>did</i>).</p>'],
['Preposição no final e What… like?','<p><i>Who are you talking <b>to</b>? Where are you <b>from</b>?</i> <i>What\'s it <b>like</b>?</i> = Como é? (pede descrição).</p>'],
['Perguntas indiretas e said/told','<p>Dentro de outra frase, a ordem volta a ser afirmativa: <i>Do you know where <b>she lives</b>?</i> (não <s>where does she live</s>). Discurso indireto: <i>She <b>said</b> (that) she was tired. She <b>told me</b> (that) she was tired.</i> <b>tell</b> precisa de pessoa.</p>']],
ex:[['Why didn\'t you call me?','Por que você não me ligou?'],['Who told you that?','Quem te contou isso?'],['What are you looking for?','O que você está procurando?'],['How long does it take to get there?','Quanto tempo leva para chegar lá?'],['Can you tell me where the station is?','Pode me dizer onde fica a estação?']],
trap:['<s>Who did call you?</s> → <b>Who called you?</b>','<s>Do you know where is the bank?</s> → <b>where the bank is</b>','<s>She said me…</s> → <b>She told me…</b> / <b>She said…</b>'],
drill:[['Where ___ you live?','do'],['Who ___ (break) the window? (passado, who = sujeito)','broke'],['Who ___ you meet at the party?','did'],['What is the weather ___? (como está)','like'],['Do you know what time it ___?','is'],['He ___ me that he was busy.','told']],
quiz:[['Pergunta indireta correta:',['Do you know where is the hotel?','Do you know where the hotel is?','Do you know where does the hotel is?','Do you know the hotel where is?'],1,'Ordem afirmativa depois de <i>where</i>.'],
['"Quem ligou?"',['Who did call?','Who called?','Who does called?','Who calls did?'],1,'<i>who</i> sujeito → sem <i>did</i>.'],
['"Com quem você está falando?"',['Who are you talking?','Who are you talking to?','To who you are talking?','Who you are talking to?'],1,'Preposição vai para o fim.'],
['Escolha:',['She said me she was ill.','She told she was ill.','She told me she was ill.','She said to me that was ill.'],2,'<b>tell + pessoa</b>.']],
cards:[['What\'s it like?','Como é?'],['How long does it take?','Quanto tempo leva?'],['Who saw you? × Who did you see?','Quem te viu? × Quem você viu?'],['Do you know where he lives?','Você sabe onde ele mora?'],['say × tell','say something / tell someone']]},

{t:'-ing e to; go, get, do, make, have',u:[50,57],
intro:'Alguns verbos pedem <b>-ing</b> depois, outros pedem <b>to + verbo</b>. Também veja os usos de cinco verbos coringa: <i>go, get, do, make, have</i>.',
pts:[['verbo + -ing','<p><i>enjoy, finish, stop, mind, suggest, keep</i> + -ing: <i>I enjoy <b>dancing</b>. Do you mind <b>waiting</b>?</i></p>'],
['verbo + to','<p><i>want, need, decide, hope, plan, learn, promise, would like</i> + to: <i>I want <b>to go</b>. She decided <b>to stay</b>.</i> <b>want/tell/ask someone to</b>: <i>I want <b>you to</b> help me.</i></p>'],
['to para finalidade','<p>"Para" indicando objetivo = <b>to</b>: <i>I went to the shop <b>to buy</b> bread</i> (não <s>for buy</s>).</p>'],
['do × make, get, go, have','<p><b>do</b>: tarefas e atividades (<i>do homework, do the shopping, do exercise</i>). <b>make</b>: criar/produzir (<i>make a cake, make a mistake, make a decision</i>). <b>get</b> = conseguir, receber, ficar, chegar (<i>get a job, get tired, get home</i>). <b>go -ing</b>: <i>go swimming, go shopping</i>.</p>']],
ex:[['I finished reading the book.','Terminei de ler o livro.'],['We\'re planning to travel in July.','Estamos planejando viajar em julho.'],['My boss asked me to stay late.','Meu chefe me pediu para ficar até tarde.'],['I\'m saving money to buy a car.','Estou guardando dinheiro para comprar um carro.'],['Sorry, I made a mistake.','Desculpe, cometi um erro.']],
trap:['<s>I enjoy to swim.</s> → <b>I enjoy swimming.</b>','<s>I want that you come.</s> → <b>I want you to come.</b>','<s>I went for buy milk.</s> → <b>to buy</b>','<s>do a mistake</s> → <b>make a mistake</b>'],
drill:[['I enjoy ___ (cook).','cooking'],['She wants ___ (learn) French.','to learn'],['Have you finished ___ (eat)?','eating'],['I went to the bank ___ get some money.','to'],['Don\'t worry, everybody ___ mistakes.','makes'],['I need to ___ my homework tonight.','do']],
quiz:[['Escolha:',['I decided buying a car.','I decided to buy a car.','I decided buy a car.','I decided for buy a car.'],1,'<i>decide</i> + <b>to</b>.'],
['"Eu quero que você venha."',['I want that you come.','I want you come.','I want you to come.','I want you coming.'],2,'<b>want + pessoa + to</b>.'],
['do ou make: "___ a cake"',['do','make','get','have'],1,'Produzir algo: <b>make</b>.'],
['"Você se importa de esperar?"',['Do you mind to wait?','Do you mind waiting?','Do you mind wait?','Are you mind waiting?'],1,'<i>mind</i> + <b>-ing</b>.']],
cards:[['enjoy / finish / stop + ?','-ing'],['want / decide / hope + ?','to + verbo'],['to (finalidade)','para: I came to learn.'],['make a mistake / a decision','cometer um erro / tomar uma decisão'],['get home / get tired','chegar em casa / ficar cansado']]},

{t:'Pronomes e possessivos',u:[58,63],
intro:'Pronomes sujeito e objeto, adjetivos e pronomes possessivos, reflexivos e o <b>\'s</b> de posse.',
pts:[['Sujeito × objeto','<p>Sujeito: <i>I, you, he, she, it, we, they</i>. Objeto (depois do verbo ou preposição): <i>me, you, him, her, it, us, them</i>. <i><b>She</b> loves <b>him</b>. Look at <b>me</b>.</i></p>'],
['my × mine','<p>Antes de substantivo: <i>my, your, his, her, its, our, their</i> (<i>my car</i>). Sozinho: <i>mine, yours, his, hers, ours, theirs</i> (<i>It\'s <b>mine</b></i>). Pergunta: <i><b>Whose</b> is this?</i> (De quem é?)</p>'],
['Reflexivos','<p><i>myself, yourself, himself, herself, itself, ourselves, yourselves, themselves</i>: quando sujeito e objeto são a mesma pessoa (<i>I cut <b>myself</b></i>) ou para dizer "sozinho" (<i>by myself</i>).</p>'],
['\'s de posse','<p>Pessoa + <b>\'s</b>: <i>Ana\'s car</i> (o carro da Ana). Plural com -s: só apóstrofo (<i>my parents\' house</i>).</p>']],
ex:[['Can you help me?','Você pode me ajudar?'],['This isn\'t my bag. Mine is black.','Esta não é minha bolsa. A minha é preta.'],['Whose phone is this? — It\'s hers.','De quem é este telefone? — É dela.'],['He lives by himself.','Ele mora sozinho.'],['This is my sister\'s husband.','Este é o marido da minha irmã.']],
trap:['<s>Me and John went.</s> (informal) → <b>John and I went.</b>','<s>the car of my father</s> → <b>my father\'s car</b>','<s>It\'s my.</s> → <b>It\'s mine.</b>'],
drill:[['I know Maria. I see ___ every day.','her'],['Is this your pen? — Yes, it\'s ___.','mine'],['___ book is this? — It\'s Tom\'s.','whose'],['They built the house ___. (eles mesmos)','themselves'],['This is ___ (Peter) car. (posse, escreva Peter + \'s)','peter\'s'],['We love our dog. ___ name is Max.','its']],
quiz:[['Escolha:',['Give it to I.','Give it to me.','Give it to my.','Give it to mine.'],1,'Depois de preposição: objeto <b>me</b>.'],
['"Essas chaves são suas?"',['Are these keys your?','Are these keys yours?','Are these your\'s keys?','Are these keys you?'],1,'Sozinho: <b>yours</b>.'],
['"A casa dos meus pais":',['my parents\'s house','my parent\'s house','my parents\' house','the house of my parents\'s'],2,'Plural com -s: só apóstrofo.'],
['"Ela se machucou."',['She hurt her.','She hurt herself.','She hurt sheself.','She hurt hers.'],1,'Reflexivo: <b>herself</b>.']],
cards:[['I · me · my · mine · myself','eu · me · meu · o meu · eu mesmo'],['she · her · her · hers · herself','ela · a/lhe · dela · o dela · ela mesma'],['they · them · their · theirs','eles · os/lhes · deles · o deles'],['Whose is this?','De quem é isto?'],['by myself','sozinho']]},

{t:'Artigos e substantivos',u:[64,72],
intro:'<b>a/an</b>, <b>the</b> ou nada? Contáveis e incontáveis, plurais e o uso de artigos com lugares e generalizações.',
pts:[['a × an','<p><b>a</b> antes de som de consoante (<i>a car, a university</i>); <b>an</b> antes de som de vogal (<i>an apple, an hour</i>). Use com profissões: <i>She\'s <b>a</b> doctor.</i></p>'],
['Plurais','<p>+s (<i>cars</i>); -s/-sh/-ch/-x +es (<i>buses, watches</i>); consoante+y → ies (<i>cities</i>). Irregulares: <i>man → men, woman → women, child → children, person → people, foot → feet, tooth → teeth</i>.</p>'],
['Contáveis × incontáveis','<p>Incontáveis não têm plural nem <i>a/an</i>: <i>water, money, information, advice, furniture, bread</i>. Use <i>some</i> ou unidades: <i>a piece of advice, a loaf of bread</i>.</p>'],
['the × sem artigo','<p><b>the</b> quando já se sabe qual (<i>Close <b>the</b> door</i>) e para coisas únicas (<i>the sun</i>). Sem artigo para falar em geral: <i>I like <b>music</b>. <b>Dogs</b> are friendly.</i> E em <i>go to work / school / bed, go home</i>.</p>']],
ex:[['I need an umbrella.','Preciso de um guarda-chuva.'],['There are three children in the garden.','Há três crianças no jardim.'],['Can you give me some information?','Pode me dar uma informação?'],['I don\'t like coffee.','Não gosto de café (em geral).'],['The coffee in this café is excellent.','O café desta cafeteria é excelente.']],
trap:['<s>She is doctor.</s> → <b>She is a doctor.</b>','<s>an informations</s> → <b>some information</b>','<s>The life is beautiful.</s> → <b>Life is beautiful.</b>','<s>I go to the home.</s> → <b>I go home.</b>'],
drill:[['She\'s ___ engineer.','an'],['He\'s ___ teacher.','a'],['One child, two ___.','children'],['Can I give you some ___ (advice)?','advice'],['I have ___ idea!','an'],['Please close ___ window. It\'s cold.','the']],
quiz:[['a ou an: "___ hour"',['a','an','the','—'],1,'<i>hour</i> começa com som de vogal.'],
['Correto:',['I need an advice.','I need some advices.','I need some advice.','I need advices.'],2,'<i>advice</i> é incontável.'],
['"Gosto de gatos" (em geral):',['I like the cats.','I like cats.','I like a cats.','I like cat.'],1,'Generalização: plural sem artigo.'],
['Plural de "person":',['persons','people','peoples','persones'],1,'O plural comum de person é <b>people</b>.']],
cards:[['a university / an hour','o som é que importa'],['child → ?','children'],['incontáveis comuns','money, water, information, advice, furniture'],['a piece of advice','um conselho'],['go home / go to bed','ir para casa / ir dormir']]},

{t:'Determinantes e quantificadores',u:[73,83],
intro:'<i>this/that, some/any, nobody/nothing, every/all, both/either/neither, much/many, a little/a few</i>: palavras que dizem qual e quanto.',
pts:[['this, that, these, those','<p>Perto: <i>this</i> (sing.) / <i>these</i> (pl.). Longe: <i>that</i> / <i>those</i>. <b>one/ones</b> evita repetir: <i>I like the red one.</i></p>'],
['some × any × no','<p><b>some</b> em afirmativas e ofertas (<i>Would you like some tea?</i>); <b>any</b> em negativas e perguntas (<i>I don\'t have any money</i>); <b>no</b> = not any (<i>I have <b>no</b> money</i>). Compostos: <i>somebody, anything, nowhere, nothing</i>.</p>'],
['much × many × a lot','<p><b>many</b> + contáveis (<i>many books</i>); <b>much</b> + incontáveis (<i>much time</i>), sobretudo em negativas e perguntas. <b>a lot of</b> serve para os dois. <b>a few</b> (contáveis) e <b>a little</b> (incontáveis) = um pouco/alguns; sem <i>a</i> = quase nenhum.</p>'],
['every, all, both, either, neither','<p><b>every</b> + singular (<i>every day</i>); <b>all</b> + plural (<i>all students</i>). De dois: <b>both</b> (os dois), <b>either</b> (qualquer um dos dois), <b>neither</b> (nenhum dos dois).</p>']],
ex:[['These shoes are too small. Do you have bigger ones?','Estes sapatos estão pequenos. Tem maiores?'],['There isn\'t anybody at home.','Não tem ninguém em casa.'],['How many people came? — Not many.','Quantas pessoas vieram? — Não muitas.'],['I have a few friends in Rio.','Tenho alguns amigos no Rio.'],['Neither of my brothers lives here.','Nenhum dos meus dois irmãos mora aqui.']],
trap:['<s>I don\'t have no money.</s> → <b>I don\'t have any money</b> / <b>I have no money</b>.','<s>How much books?</s> → <b>How many books?</b>','<s>every days</s> → <b>every day</b>'],
drill:[['Is there ___ milk in the fridge? (pergunta)','any'],['I bought ___ apples. (afirmativa)','some'],['How ___ money do you have?','much'],['How ___ brothers have you got?','many'],['I speak ___ Japanese. Just a little.','a little'],['___ of my parents are teachers. (os dois)','both']],
quiz:[['"Não vi ninguém."',['I didn\'t see nobody.','I didn\'t see anybody.','I saw anybody.','I didn\'t saw anybody.'],1,'Negativa + <b>anybody</b> (ou <i>I saw nobody</i>).'],
['"Quanto tempo nós temos?"',['How many time do we have?','How much time do we have?','How much times we have?','How many times have we?'],1,'<i>time</i> incontável → <b>much</b>.'],
['Escolha: "___ student has a book."',['All','Every','Both','Many'],1,'<b>every</b> + singular.'],
['"Tenho poucos amigos (quase nenhum)":',['I have a few friends.','I have few friends.','I have a little friends.','I have little friends.'],1,'<b>few</b> sem <i>a</i> = quase nenhum.']],
cards:[['this / these · that / those','este(s) · aquele(s)'],['some / any / no','afirm. / neg. e perg. / nenhum'],['much / many','incontável / contável'],['a few / a little','alguns / um pouco'],['both / either / neither','ambos / qualquer um / nenhum dos dois']]},

{t:'Adjetivos, advérbios e comparação',u:[84,91],
intro:'Adjetivos descrevem coisas; advérbios descrevem ações. Também veja comparativos, superlativos, <i>enough</i> e <i>too</i>.',
pts:[['Posição do adjetivo','<p>O adjetivo vem antes do substantivo e não tem plural: <i>a <b>big</b> house, two <b>big</b> houses</i>. Depois de <i>be, look, feel, seem</i>: <i>You look tired.</i></p>'],
['Advérbios em -ly','<p><i>quick → quickly, careful → carefully, easy → easily</i>. Irregulares: <i>good → <b>well</b>, fast → fast, hard → hard</i>. <i>She speaks English <b>well</b></i> (não <s>good</s>).</p>'],
['Comparativo e superlativo','<p>Curtos: <i>old → old<b>er</b> → the old<b>est</b></i>; <i>big → bigger, happy → happier</i>. Longos: <i><b>more</b> expensive → <b>the most</b> expensive</i>. Irregulares: <i>good → better → the best; bad → worse → the worst; far → further</i>. Comparação: <i>older <b>than</b></i>; igualdade: <i><b>as</b> tall <b>as</b></i>.</p>'],
['enough × too','<p><b>too</b> = demais (<i>too hot</i>). <b>enough</b> = suficiente: depois do adjetivo (<i>old enough</i>) e antes do substantivo (<i>enough money</i>).</p>']],
ex:[['She drives very carefully.','Ela dirige com muito cuidado.'],['My car is older than yours.','Meu carro é mais velho que o seu.'],['This is the most beautiful place in the city.','Este é o lugar mais bonito da cidade.'],['He isn\'t as tall as his brother.','Ele não é tão alto quanto o irmão.'],['The coffee is too hot to drink.','O café está quente demais para beber.']],
trap:['<s>more big</s> → <b>bigger</b>','<s>She sings very good.</s> → <b>very well</b>','<s>enough old</s> → <b>old enough</b>','<s>bigger that</s> → <b>bigger than</b>'],
drill:[['He drives very ___ (careful).','carefully'],['She speaks French very ___ (good).','well'],['Brazil is ___ (big) than Argentina.','bigger'],['This is the ___ (good) pizza in town.','best'],['This film is ___ interesting than the book. (mais)','more'],['I can\'t buy it. I don\'t have ___ money.','enough']],
quiz:[['Comparativo de "good":',['gooder','more good','better','best'],2,'Irregular: <b>better</b>.'],
['Escolha:',['He runs quick.','He runs quickly.','He quickly runs fast.','He runs quicker than.'],1,'Descreve ação: advérbio <b>quickly</b>.'],
['"o mais caro":',['the expensivest','the more expensive','the most expensive','most expensive than'],2,'Adjetivo longo: <b>the most</b>.'],
['"Ele não tem idade suficiente."',['He isn\'t enough old.','He isn\'t old enough.','He isn\'t too old.','He is old enough not.'],1,'<b>adjetivo + enough</b>.']],
cards:[['quick → quickly','rápido → rapidamente'],['good → well','bom → bem'],['good · better · the best','bom · melhor · o melhor'],['as … as','tão … quanto'],['too / enough','demais / suficiente']]},

{t:'Ordem das palavras',u:[92,95],
intro:'A ordem em inglês é rígida: sujeito + verbo + objeto, e advérbios têm lugar certo. Também veja <i>still, yet, already</i> e verbos com dois objetos.',
pts:[['Verbo e objeto juntos','<p>Não separe o verbo do objeto: <i>He speaks English very well</i> (não <s>He speaks very well English</s>). Lugar antes de tempo: <i>I go <b>to work</b> <b>every day</b>.</i></p>'],
['Advérbios de frequência','<p>Antes do verbo principal (<i>I <b>often</b> go</i>) e depois de <i>be</i> e auxiliares (<i>She is <b>always</b> late. I have <b>never</b> seen it.</i>).</p>'],
['still, yet, already','<p><b>still</b> = ainda (continua): <i>It\'s still raining.</i> <b>yet</b> = ainda (neg.) / já (perg.), no fim. <b>already</b> = já, antes do esperado: <i>I\'ve already paid.</i></p>'],
['give me it?','<p>Com dois objetos: <i>Give <b>me that book</b></i> ou <i>Give <b>it to me</b></i>. Com pronome <i>it/them</i>, use <b>to</b>: <s>Give me it</s> → <i>Give it to me.</i></p>']],
ex:[['I like Italian food very much.','Gosto muito de comida italiana.'],['We usually have dinner at 8.','Geralmente jantamos às 8.'],['Are you still working there?','Você ainda trabalha lá?'],['Has the bus arrived yet?','O ônibus já chegou?'],['Can you send it to me?','Você pode enviar para mim?']],
trap:['<s>I like very much pizza.</s> → <b>I like pizza very much.</b>','<s>She always is late.</s> → <b>She is always late.</b>'],
drill:[['She ___ (always) late. (is + always)','is always'],['I ___ (never / eat) meat. (duas palavras)','never eat'],['Is your father ___ in hospital? (ainda)','still'],['Have you finished ___? (já, no fim)','yet'],['I\'ve ___ seen this film. (já)','already'],['Please give it ___ me.','to']],
quiz:[['Ordem correta:',['I play very well tennis.','I play tennis very well.','I very well play tennis.','I tennis play very well.'],1,'Verbo + objeto juntos.'],
['Escolha:',['They go often to the cinema.','They often go to the cinema.','They go to the cinema often always.','Often they to the cinema go.'],1,'Frequência antes do verbo principal.'],
['"Ainda está chovendo."',['It\'s yet raining.','It\'s still raining.','It\'s already raining.','It still is raining yet.'],1,'Continuidade: <b>still</b>.'],
['Correto:',['Give me it.','Give it me.','Give it to me.','Give to me it.'],2,'Pronome <i>it</i> + <b>to me</b>.']],
cards:[['S + V + O + lugar + tempo','I met Ana at the café yesterday.'],['She is always…','frequência depois de be'],['still','ainda (continua)'],['yet','ainda (neg.) / já (perg.)'],['already','já']]},

{t:'Preposições de tempo e lugar',u:[96,106],
intro:'<i>at, on, in</i> para tempo e lugar; preposições de movimento e posição; e combinações fixas como <i>good at, afraid of, listen to</i>.',
pts:[['Tempo: at / on / in','<p><b>at</b> + horas e momentos (<i>at 8 o\'clock, at night, at the weekend</i>). <b>on</b> + dias e datas (<i>on Monday, on 5 May</i>). <b>in</b> + meses, anos, estações, partes do dia (<i>in July, in 2020, in the morning</i>).</p>'],
['Duração e sequência','<p><i>from… to, until, since, for</i>; <i>before, after</i>; <b>during</b> + substantivo (<i>during the film</i>); <b>while</b> + frase (<i>while I was eating</i>).</p>'],
['Lugar: in / at / on','<p><b>in</b> = dentro de espaço (<i>in the kitchen, in Brazil</i>). <b>at</b> = ponto, evento, endereço (<i>at the bus stop, at a party, at home, at work</i>). <b>on</b> = superfície (<i>on the table, on the wall, on the 2nd floor</i>). Movimento: <b>to</b> (<i>go to Paris</i>), mas <i>go home</i> sem <i>to</i>.</p>'],
['Combinações fixas','<p>Adjetivo + prep.: <i>good at, afraid of, interested in, married to</i>. Verbo + prep.: <i>listen to, look at, wait for, talk to, depend on</i>. Depois de preposição, verbo vai com <b>-ing</b>: <i>I\'m good at <b>cooking</b>.</i></p>']],
ex:[['The meeting is on Friday at 10.','A reunião é na sexta às 10.'],['I was born in 1995.','Nasci em 1995.'],['She\'s waiting at the bus stop.','Ela está esperando no ponto de ônibus.'],['Your keys are on the table.','Suas chaves estão na mesa.'],['Are you interested in learning Spanish?','Você tem interesse em aprender espanhol?']],
trap:['<s>in Monday</s> → <b>on Monday</b>','<s>at the morning</s> → <b>in the morning</b>','<s>I\'m waiting you.</s> → <b>waiting for you</b>','<s>during I was sleeping</s> → <b>while I was sleeping</b>'],
drill:[['The film starts ___ 9 o\'clock.','at'],['My birthday is ___ March.','in'],['See you ___ Saturday!','on'],['I\'m ___ home now.','at'],['Listen ___ this song!','to'],['I\'m very good ___ maths.','at']],
quiz:[['"___ the weekend" (inglês britânico):',['in','on','at','by'],2,'Britânico: <b>at the weekend</b> (americano: on).'],
['"Na parede":',['in the wall','on the wall','at the wall','to the wall'],1,'Superfície: <b>on</b>.'],
['Escolha:',['I\'m afraid from dogs.','I\'m afraid of dogs.','I\'m afraid with dogs.','I\'m afraid about dogs.'],1,'<b>afraid of</b>.'],
['"Ela dormiu durante o filme."',['She slept while the film.','She slept during the film.','She slept for the film.','She slept since the film.'],1,'<b>during</b> + substantivo.']],
cards:[['at 5 pm · on Monday · in May','hora · dia · mês'],['in the kitchen · at work · on the table','dentro · ponto/lugar · superfície'],['during × while','+ substantivo × + frase'],['good at / afraid of / interested in','bom em / com medo de / interessado em'],['wait for / listen to / look at','esperar / ouvir / olhar']]},

{t:'Phrasal verbs, conjunções e orações',u:[107,114],
intro:'Fechando o nível: phrasal verbs básicos, conectores (<i>and, but, so, because, when</i>), condicionais com <i>if</i> e orações relativas (<i>who, which, that</i>).',
pts:[['Phrasal verbs','<p>Verbo + partícula com sentido novo: <i>get up, sit down, turn on, put on, take off, look for, give up</i>. Com objeto, a partícula pode ir antes ou depois: <i>put on your shoes / put your shoes on</i>. Com pronome, só no meio: <i>put <b>them</b> on</i>.</p>'],
['Conectores e when','<p><i>and</i> (e), <i>but</i> (mas), <i>or</i> (ou), <i>so</i> (então, resultado), <i>because</i> (porque, causa). Com <b>when</b> e <b>if</b> falando do futuro, use presente: <i>When I <b>get</b> home, I\'ll call you.</i></p>'],
['If: real × imaginário','<p>Possível: <i>If it <b>rains</b>, we <b>will</b> stay home.</i> Imaginário/irreal: <i>If I <b>had</b> money, I <b>would</b> travel.</i> (passado + would).</p>'],
['Orações relativas','<p><b>who</b> para pessoas, <b>which</b> para coisas, <b>that</b> para ambos: <i>the man <b>who</b> lives next door, the book <b>that</b> I bought</i>. Quando o relativo é objeto, pode sumir: <i>the people <b>we met</b></i>.</p>']],
ex:[['Turn off the light, please.','Apague a luz, por favor.'],['I was tired, so I went to bed.','Eu estava cansado, então fui dormir.'],['If you see Ana, tell her to call me.','Se você vir a Ana, diga para ela me ligar.'],['If I were rich, I would buy a boat.','Se eu fosse rico, compraria um barco.'],['The hotel we stayed at was great.','O hotel em que ficamos era ótimo.']],
trap:['<s>When I will arrive, I\'ll call.</s> → <b>When I arrive</b>','<s>If I would have money…</s> → <b>If I had money…</b>','<s>Put on them.</s> → <b>Put them on.</b>','<s>the man which…</s> → <b>the man who/that…</b>'],
drill:[['It\'s cold. Put ___ your jacket.','on'],['I stayed at home ___ I was ill.','because'],['If it ___ (rain) tomorrow, we\'ll stay at home.','rains'],['If I ___ (have) a car, I would drive to work.','had'],['The woman ___ lives next door is a doctor.','who|that'],['I\'ll call you when I ___ (get) home.','get']],
quiz:[['Escolha:',['If I will see him, I\'ll tell him.','If I see him, I\'ll tell him.','If I saw him, I\'ll tell him.','If I see him, I tell him tomorrow.'],1,'<b>If + presente, will</b>.'],
['"Se eu soubesse, eu te diria."',['If I knew, I would tell you.','If I know, I would tell you.','If I knew, I will tell you.','If I would know, I tell you.'],0,'Irreal: <b>passado + would</b>.'],
['Relativo para coisa:',['the car who I bought','the car which I bought','the car whose I bought','the car what I bought'],1,'Coisa: <b>which/that</b>.'],
['Com pronome:',['Take off it.','Take it off.','Take of it.','It take off.'],1,'Pronome no meio: <b>take it off</b>.']],
cards:[['put on / take off','vestir / tirar (roupa)'],['turn on / turn off','ligar / desligar'],['so × because','resultado × causa'],['If it rains, we\'ll…','Se chover, nós vamos…'],['If I had…, I would…','Se eu tivesse…, eu iria…']]}
]});
